// categories.js - List of all valid categories
const VALID_CATEGORIES = new Set([
    "CLS10TELUGU", "CLS10HINDI", "CLS10ENGLISH", "CLS10MATHS", "CLS10SCIENCE", "CLS10SOCIAL",
    "CLS10BRIDGE", "CLS10POLYTECHNIC", "CLS10FORMULAS",

    "CLS11MPC-PHYSICS", "CLS11MPC-MATHS1A", "CLS11MPC-MATHS1B", "CLS11MPC-CHEMISTRY",
    "CLS11MPC-EAMCET", "CLS11MPC-JEEMAINS", "CLS11MPC-JEEADV",

    "CLS12MPC-PHYSICS", "CLS12MPC-MATHS2A", "CLS12MPC-MATHS2B", "CLS12MPC-CHEMISTRY",
    "CLS12MPC-EAMCET", "CLS12MPC-JEEMAINS", "CLS12MPC-JEEADV",

    "CLS11BIPC-PHYSICS", "CLS11BIPC-BOTANY", "CLS11BIPC-ZOOLOGY", "CLS11BIPC-CHEMISTRY",
    "CLS11BIPC-EAPCET", "CLS11BIPC-NEET", 
    
    "CLS12BIPC-PHYSICS", "CLS12BIPC-BOTANY","CLS12BIPC-ZOOLOGY", "CLS12BIPC-CHEMISTRY", 
    "CLS12BIPC-EAPCET", "CLS12BIPC-NEET"
]);

module.exports = VALID_CATEGORIES;
