// categories.js - List of all valid categories
const VALID_CATEGORIES = new Set([
    "CLS10-TELUGU", "CLS10-HINDI", "CLS10-ENGLISH", "CLS10-MATHS", "CLS10-SCIENCE", "CLS10-SOCIAL",
    "CLS10-BRIDGE", "CLS10-POLYTECHNIC", "CLS10-FORMULAS",

    "CLS11-MPC-PHYSICS", "CLS11-MPC-MATHS1A", "CLS11-MPC-MATHS1B", "CLS11-MPC-CHEMISTRY",
    "CLS11-MPC-EAMCET", "CLS11-MPC-JEEMAINS", "CLS11-MPC-JEEADV",

    "CLS12-MPC-PHYSICS", "CLS12-MPC-MATHS2A", "CLS12-MPC-MATHS2B", "CLS12-MPC-CHEMISTRY",
    "CLS12-MPC-EAMCET", "CLS12-MPC-JEEMAINS", "CLS12-MPC-JEEADV",

    "CLS11-BIPC-PHYSICS", "CLS11-BIPC-BOTANY", "CLS11-BIPC-ZOOLOGY", "CLS11-BIPC-CHEMISTRY",
    "CLS11-BIPC-EAPCET", "CLS11-BIPC-NEET", 
    
    "CLS12-BIPC-PHYSICS", "CLS12-BIPC-BOTANY","CLS12-BIPC-ZOOLOGY", "CLS12-BIPC-CHEMISTRY", 
    "CLS12-BIPC-EAPCET", "CLS12-BIPC-NEET"
]);

module.exports = VALID_CATEGORIES;
